export default function Privacy() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#f6f8fb",
        padding: "40px 16px",
      }}
    >
      <div
        style={{
          maxWidth: 900,
          margin: "0 auto",
          background: "#fff",
          borderRadius: 16,
          padding: "28px 24px",
          border: "1px solid rgba(28,24,19,.08)",
          boxShadow: "0 10px 28px rgba(20,20,40,0.06)",
        }}
      >
        <div style={{ marginBottom: 14 }}>
          <a
            href="/"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
              textDecoration: "none",
              color: "#0f766e",
              fontWeight: 600,
              fontSize: 13,
            }}
          >
            <span aria-hidden="true">←</span>
            Go back
          </a>
        </div>

        <h1 style={{ marginTop: 0 }}>Privacy Policy</h1>
        <div style={{ fontSize: 13, opacity: 0.7, marginBottom: 18 }}>
          Last updated: {new Date().toLocaleDateString()}
        </div>

        <p>
          This Privacy Policy explains how BOMH Ltd, a Kenyan company (“BOMH”,
          “we”, “us”), collects, uses, and protects personal data when you use
          the Onlinegym service (“Service”).
        </p>

        <h3>1. Information we collect</h3>
        <p>
          We collect information you provide (such as your name, email, phone
          number, and gym details), and data generated by your use of the
          Service (such as members, subscriptions, and messages sent).
        </p>

        <h3>2. How we use information</h3>
        <p>
          We use information to operate the Service, provide support, process
          billing, improve features, and ensure security. We do not sell your
          data.
        </p>

        <h3>3. Data sharing</h3>
        <p>
          We may share data with service providers that help us operate the
          Service (such as hosting, email, or SMS providers). We only share what
          is necessary and require them to protect the data.
        </p>

        <h3>4. Data retention</h3>
        <p>
          We retain data for as long as your account is active or as needed to
          provide the Service, comply with legal obligations, resolve disputes,
          and enforce our agreements.
        </p>

        <h3>5. Security</h3>
        <p>
          We implement reasonable security measures to protect your data.
          However, no method of transmission or storage is 100% secure.
        </p>

        <h3>6. Your responsibilities</h3>
        <p>
          You are responsible for obtaining any necessary consent from your
          members and ensuring your use of the Service complies with applicable
          laws.
        </p>

        <h3>7. International transfers</h3>
        <p>
          Your data may be processed in countries other than your own, depending
          on our service providers. We take steps to ensure adequate protection
          of your data.
        </p>

        <h3>8. Updates to this policy</h3>
        <p>
          We may update this Privacy Policy from time to time. We will post the
          updated policy on this page.
        </p>

        <h3>9. Contact</h3>
        <p>
          If you have questions about this Privacy Policy, contact us at
          mail@onlinegym.co.
        </p>
      </div>
    </div>
  );
}
